version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test
          command: yarn test

